### ISSUE TITLE
Data loader for tabular files

### ISSUE THREAD

**Issue by nmearl** [nmearl/pyfocal#19]
Create a registry object for ingesting data files that are e.g. `csv`, `txt`, etc. This will require either

1. Creating a new `YAMLLoader` class to deal with non-fits styled data, or
2. Extending the current `YAMLLoader` to also deal with the tabular data.

See [here](https://github.com/nmearl/pyfocal/blob/1aa0bc4645f76d94e2d34ce64ae9d92998e431ef/pyfocal/interfaces/registries.py#L35) for details on current implementation.

**Comment by pllim** [comment]
This is a bit too cryptic. Exactly what kind of file formats are you expecting? Is it possible to use any existing parser, say, from JWST pipeline? We have to be careful not to re-invent the wheel here.

**Comment by nmearl** [comment]
Okay. Well, since we're generally leveraging the astropy library for most all our functionality, I think we ought to stay within that realm.

For instance, tabular data is easily read into an [astropy table object](http://docs.astropy.org/en/stable/api/astropy.table.Table.html). From there, it's possible to export the normalized object as an ndarray that can be used in the creation of the `Data` object we use in Pyfocal.

The associated yaml file should contain definitions for how to ingest that data, e.g.

```yaml
--- !CustomLoader
name: Generic Table
extension: [csv, txt]
data:
  col: 0
  unit: "Jy"
dispersion:
  col: 1
  unit: "Angstrom"
uncertainty:
  col: 2
meta:
  author: "Nicholas Earl"
```
